# Generated by Django 4.0.3 on 2022-03-27 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_alter_habit_steak_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habit',
            old_name='steak_count',
            new_name='streak_count',
        ),
    ]
